language: cpp
compiler: gcc
deploy:
  provider: releases
  api_key:
    secure: # 使用自己的 key 替换
  file:
    - "bin/${DIST}/fibjs_${DIST_FILENAME}"
    - "bin/${DIST}/installer_${DIST_FILENAME}.sh"
  skip_cleanup: true
  on:
    tags: true
    repo: xicilion/fibjs
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
env: 
  - DIST=Linux_amd64_release;DIST_FILENAME=linux_x64;
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      env:
        - DIST=Darwin_amd64_release;DIST_FILENAME=darwin
install:
  - git submodule init
  - git submodule update
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.9; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-4.9; fi
script:
  - sh build -j2
  - cp "bin/${DIST}/fibjs" "bin/${DIST}/fibjs_${DIST_FILENAME}"
  - chmod a+x "bin/${DIST}/fibjs_${DIST_FILENAME}"
  - cp "bin/${DIST}/installer.sh" "bin/${DIST}/installer_${DIST_FILENAME}.sh"
  - chmod a+x "bin/${DIST}/installer_${DIST_FILENAME}.sh"
  # run test
  - cd test && ../bin/${DIST}/fibjs main.js
